# Generated by Django 4.2.3 on 2023-07-18 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='phone',
        ),
        migrations.AlterField(
            model_name='card',
            name='address',
            field=models.CharField(max_length=800),
        ),
    ]
