# Generated by Django 5.0.7 on 2024-07-25 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0003_rename_address_card_mensaje'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='mensaje',
        ),
        migrations.AlterField(
            model_name='card',
            name='email',
            field=models.EmailField(max_length=50),
        ),
    ]
