# Generated by Django 5.0.7 on 2024-07-25 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0004_remove_card_mensaje_alter_card_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='email',
        ),
        migrations.AddField(
            model_name='card',
            name='excel_file',
            field=models.FileField(default='default_value', upload_to='uploads/'),
        ),
    ]
